### ISSUE TITLE
bitrot -- installation fails

### ISSUE THREAD

**Issue by mengwong** [citizennet/purescript-template#1]
came here from https://purescript-resources.readthedocs.io/en/latest/ui.html

```
┌─[20230307-14:01:40]   [mengwong@rosegold:~/src/purescript/citizennet]
└─[0] <git:(master 5ff7a7c) > yarn && yarn build
yarn install v1.22.19
info No lockfile found.
[1/4] �  Resolving packages...
warning pulp > sorcery > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning pulp > browserify > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[2/4] �  Fetching packages...
[3/4] �  Linking dependencies...
[4/4] �  Building fresh packages...
error /Users/mengwong/src/purescript/citizennet/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.12.5
Arguments:
Directory: /Users/mengwong/src/purescript/citizennet/node_modules/purescript
Output:
/Users/mengwong/src/purescript/citizennet/node_modules/zen-observable/lib/Observable.js:65
      throw e;
      ^

TypeError: Cannot read properties of undefined (reading 'has')
    at getCurrentTask (/Users/mengwong/src/purescript/citizennet/node_modules/install-purescript-cli/index.js:326:24)
    at Object.error (/Users/mengwong/src/purescript/citizennet/node_modules/install-purescript-cli/index.js:480:17)
    at notifySubscription (/Users/mengwong/src/purescript/citizennet/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/Users/mengwong/src/purescript/citizennet/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/Users/mengwong/src/purescript/citizennet/node_modules/zen-observable/lib/Observable.js:240:7)
    at Object.error (/Users/mengwong/src/purescript/citizennet/node_modules/install-purescript/index.js:93:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.1.0
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by davezuch** [comment]
Hi @mengwong, thanks for bringing this to our attention. We'll probably archive this repo and have it removed from that doc, as it isn't used or maintained.

**Comment by davezuch** [comment]
Opened a PR to remove it: https://github.com/justinwoo/purescript-resources/pull/3
